import type { Metadata } from "next";
import "./globals.css";

const aueConnection =
  process.env.NEXT_PUBLIC_AEM_CONNECTION ?? process.env.NEXT_PUBLIC_AEM_HOST;
const aueService =
  process.env.NEXT_PUBLIC_SERVICE ?? 'https://universal-editor-service.adobe.io';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <head>
        <script src="https://universal-editor-service.adobe.io/cors.js" async></script>
        {aueConnection ? (
          <meta
            name="urn:adobe:aue:system:aemconnection"
            content={`aem:${aueConnection}`}
          />
        ) : null}
        {aueService ? (
          <meta
            name="urn:adobe:aue:config:service"
            content={`service:${aueService}`}
          />
        ) : null}
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
