import type { Metadata } from "next";
import "./globals.css";
import { INSURANCE_JOURNEY_MODEL_DEFINITION } from "./lib/universalEditorModels";
import { isUniversalEditorRequest } from "./lib/universalEditor";

const aueConnection =
  process.env.NEXT_PUBLIC_AEM_CONNECTION ?? process.env.NEXT_PUBLIC_AEM_HOST;

const aem = process.env.AEM_HOST!;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const universalEditorModelDefinitionJson = JSON.stringify(
  INSURANCE_JOURNEY_MODEL_DEFINITION,
);

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isUniversalEditor = await isUniversalEditorRequest();

  return (
    <html
      lang="en"
      className={
        isUniversalEditor
          ? "caravan-ue-document antialiased"
          : "h-full antialiased"
      }
      suppressHydrationWarning
    >
      <head>
        <script
          src="https://universal-editor-service.adobe.io/cors.js"
          async
        ></script>
        {aueConnection ? (
          <meta
            name="urn:adobe:aue:system:aemconnection"
            content={`aem:${aueConnection}`}
            data-rh="true"
          />
        ) : null}
        {/* <meta
          name="urn:adobe:aue:config:service"
          content="https://localhost:8000"
        /> */}
        <script
          type="application/vnd.adobe.aue.model+json"
          dangerouslySetInnerHTML={{
            __html: universalEditorModelDefinitionJson,
          }}
        />
        <meta name="test" content={`aem:${aem}`} />
      </head>
      <body
        className={
          isUniversalEditor ? "caravan-ue-body flex flex-col" : "flex flex-col"
        }
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
